source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'require_all'
gem 'thin'
gem 'bcrypt'
gem 'puma'
gem 'rack'
gem 'pg'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'sysrandom'
gem 'rake'
gem 'sqlite3', '~> 1.3.6'
gem 'faker'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
